Force the removal of the rename script
It is modified by the sed(1) command and git-rm(1) can complain about that
depending on your local configuration:

   error: the following file has local modifications:
       rename-vmod-script
   (use --cached to keep the file, or -f to force removal)